### ISSUE TITLE
test: fix coverage

### ISSUE THREAD

**Issue by TheAlexLichter** [nuxt-community/separate-env-module#2]
Currently, `lib/modules.js` isn't recognized as tested file and no coverage is emitted. If you add force-collection with 
```
"collectCoverageFrom": [
      "**/lib/**"
    ],
```
jest will spit out an error message:
```
Running coverage on untested files...Failed to collect coverage from /home/mannil/Programming/JS/nuxt-separate-env/lib/module.js
ERROR: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
STACK: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
```

This behavior ~doesn't~ does also occur in [feed-module](https://github.com/nuxt-community/feed-module)

**Comment by kurokochin** [comment]
I'll check it out and see if I can help!

**Comment by TheAlexLichter** [comment]
@kurokochin Great, thanks a lot! :relaxed:

**Comment by TheAlexLichter** [comment]
Dang, looks like feed module is [also affected](https://codecov.io/gh/nuxt-community/feed-module/commits)

**Comment by TheAlexLichter** [comment]
If I use 

```js
"collectCoverageFrom": [
      "**/lib/**"
    ],
```

and refactor all ESM syntax calls back to `require`/`modules.exports`, the file will have 0% coverage.

![image](https://user-images.githubusercontent.com/640208/46920580-2bdbfd80-cfe8-11e8-9135-574e2da1ac00.png)

---

Switching from `nuxt-edge` to `nuxt` doesn't resolve the problem.

**Comment by TheAlexLichter** [comment]
Related: https://github.com/nuxt/nuxt.js/issues/4119

**Comment by TheAlexLichter** [comment]
Will close this one here as it depends on the issue linked above
